/**
 * GraphSAGE Layer for FPGA - INT8 with POWER-OF-TWO SCALES
 * 
 * OPTIMIZED VERSION: Uses bit-shifts instead of multipliers for scale conversion.
 * This eliminates the ~500-700 DSP48s used for scale multiplications.
 * 
 * Key differences from graphsage_layer_int8.h:
 *   - Scale values are constrained to powers of 2
 *   - Scale multiplication replaced with bit-shift
 *   - Shorter critical path → better timing
 *   - Lower DSP usage
 * 
 * Usage:
 *   1. Generate PO2 parameters: python prepare_ptq_int8_parameters.py --po2-scales
 *   2. Compile with: -DUSE_PO2_SCALES
 *   3. Optionally enable optimized bitwidths: -DUSE_OPTIMIZED_BITWIDTHS
 */

#pragma once

#include <stdint.h>
#include <ap_int.h>

#ifndef __SYNTHESIS__
#include <cstdio>
#endif

// ============================================================================
// OPTIMIZED BIT-WIDTHS SUPPORT
// ============================================================================
//
// To use auto-generated optimized bit-widths:
//   1. Run: cd src && python optimize_bitwidths_int8.py
//   2. Pass -DUSE_OPTIMIZED_BITWIDTHS to the compiler
//
// This will include auto_generated_bitwidths.h and use OPT_* values.

#ifdef USE_OPTIMIZED_BITWIDTHS
#include "auto_generated_bitwidths.h"
#endif

// ============================================================================
// Design Space Exploration Configuration
// ============================================================================
// Include DSE config if available (generated by explore_design_space.py)
#ifdef DSE_CONFIG
#include "dse_config.h"
#endif

// Default pragma parameters (used if DSE config not provided)
#ifndef DSE_UNROLL_NODES
#define DSE_UNROLL_NODES 0  // 0 = complete unroll
#endif

#ifndef DSE_UNROLL_FEATURES_AGG
#define DSE_UNROLL_FEATURES_AGG 0
#endif

#ifndef DSE_UNROLL_FEATURES_LIN
#define DSE_UNROLL_FEATURES_LIN 0
#endif

#ifndef DSE_UNROLL_FEATURES_RELU
#define DSE_UNROLL_FEATURES_RELU 0
#endif

#ifndef DSE_UNROLL_OUTPUTS
#define DSE_UNROLL_OUTPUTS 1  // 1 = pipeline (default), >1 = partial unroll, 0 = complete unroll
#endif

#ifndef DSE_AGG_PIPELINE_II
#define DSE_AGG_PIPELINE_II 1
#endif

#ifndef DSE_LIN_PIPELINE_II
#define DSE_LIN_PIPELINE_II 1
#endif

#ifndef DSE_BIND_AGG_MUL
#define DSE_BIND_AGG_MUL "dsp"  // "dsp" or "fabric"
#endif

#ifndef DSE_BIND_LIN_MUL
#define DSE_BIND_LIN_MUL "fabric"  // "dsp" or "fabric"
#endif

#ifndef DSE_ALLOC_AGG_MUL_LIMIT
#define DSE_ALLOC_AGG_MUL_LIMIT -1  // -1 = unlimited
#endif

#ifndef DSE_ALLOC_LIN_MUL_LIMIT
#define DSE_ALLOC_LIN_MUL_LIMIT -1  // -1 = unlimited
#endif

// ============================================================================
// Configuration
// ============================================================================

// Map DSE configuration to standard names (if DSE config is provided)
#ifdef DSE_CONFIG
    #define NUM_NODES DSE_NUM_NODES
    #define IN_FEATURES DSE_IN_FEATURES
    #define HIDDEN_FEATURES DSE_HIDDEN_FEATURES
    #define OUT_FEATURES DSE_OUT_FEATURES
#else
    // Defaults when not using DSE
    #ifndef NUM_NODES
    #define NUM_NODES 8
    #endif

    #ifndef IN_FEATURES
    #define IN_FEATURES 16
    #endif

    #ifndef HIDDEN_FEATURES
    #define HIDDEN_FEATURES 24
    #endif

    #ifndef OUT_FEATURES
    #define OUT_FEATURES 7
    #endif
#endif

// Fixed-point configuration
#ifndef M_BITS
#define M_BITS 24  // Fractional bits for intermediate calculations
#endif

#ifndef K_BITS
#define K_BITS 12  // Adjacency scale: A_int = A_float * 2^12
#endif

// ============================================================================
// Power-of-Two Scale Shift Amounts
// ============================================================================
// 
// These replace arbitrary scale values with shift amounts.
// Formula: shift = M_BITS - log2(scale_po2)
//
// Example: If eff_scale_float = 0.0106867758
//          eff_scale_fp = 0.0106867758 * 2^24 = 179,294
//          Nearest PO2 = 2^17 = 131,072
//          Shift = 24 - 17 = 7
//
// Scale factors are model-dependent and should be provided via compiler flags (-D)
// when running DSE. The values below are defaults that may not match your model.
// DSE automatically loads shifts from build/test_vectors_ptq_int8_po2/po2_config.json

#ifndef EFF_SCALE1_SHIFT
#define EFF_SCALE1_SHIFT 7   // Default - override via -DEFF_SCALE1_SHIFT=X
#endif

#ifndef EFF_SCALE2_SHIFT
#define EFF_SCALE2_SHIFT 8   // Default - override via -DEFF_SCALE2_SHIFT=X
#endif

#ifndef BETA1_SHIFT
#define BETA1_SHIFT 17       // Default - override via -DBETA1_SHIFT=X
#endif

#ifndef BETA2_SHIFT
#define BETA2_SHIFT 12       // Corresponds to scale = 2^12 (exact!)
#endif

// ============================================================================
// Optimized Bit-Widths (from data-driven analysis or defaults)
// ============================================================================

#ifndef ADJ_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value
#define ADJ_BITS OPT_ADJ_BITS
#else
// Conservative default
#define ADJ_BITS 16          // Adjacency: 2^12 max → 13 bits + margin
#endif
#endif

#ifndef ACC_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value (typically ~22 bits)
#define ACC_BITS OPT_ACC_BITS
#else
// Conservative default
#define ACC_BITS 22          // Accumulator: actual max ~389k → 19 bits + margin
#endif
#endif

// ============================================================================
// Type Definitions
// ============================================================================

typedef ap_int<8>        data_t;      // INT8 activations/weights
typedef ap_int<8>        weight_t;    // INT8 weights
typedef ap_int<ADJ_BITS> adj_t;       // Scaled adjacency matrix
typedef ap_int<ACC_BITS> acc_t;       // Accumulator
typedef ap_int<ACC_BITS> bias_t;      // Bias in accumulator domain

// ============================================================================
// Helper: Clamp to INT8 range
// ============================================================================

inline data_t int8_clamp(acc_t x) {
#pragma HLS INLINE
    if (x > 127)  return data_t(127);
    if (x < -128) return data_t(-128);
    return data_t(x);
}

// ============================================================================
// PO2 Aggregation (NO MULTIPLIER for scaling!)
// ============================================================================
/**
 * Integer-only aggregation with power-of-two rescaling.
 * 
 * Formula:
 *   tmp = sum_j(adj[i,j] * feat[j,f])
 *   result = (tmp + rounding) >> shift
 * 
 * The shift replaces: (tmp * beta_fp + 2^(M-1)) >> M
 *                  =  (tmp * 2^S + 2^(M-1)) >> M
 *                  =  (tmp + 2^(M-S-1)) >> (M-S)
 *                  =  (tmp + 2^(shift-1)) >> shift
 */
template<int N_NODES, int N_FEAT>
void aggregate_int8_po2(
    const adj_t  adj_matrix[N_NODES][N_NODES],
    const data_t features[N_NODES][N_FEAT],
    data_t       agg_out[N_NODES][N_FEAT],
    const int    shift_amount
) {
#pragma HLS INLINE

    // Pre-compute rounding constant
    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

AGG_I:
    for (int i = 0; i < N_NODES; i++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    AGG_F:
        for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_AGG > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_AGG
#elif DSE_UNROLL_FEATURES_AGG == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_AGG_PIPELINE_II
#endif

            acc_t tmp = 0;

        AGG_J:
            for (int j = 0; j < N_NODES; j++) {
#pragma HLS UNROLL
#pragma HLS BIND_OP variable=tmp op=mul impl=DSE_BIND_AGG_MUL
                // INT16 × INT8 → ACC (no scale multiplier!)
#if DSE_ALLOC_AGG_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_AGG_MUL_LIMIT operation
#endif
                tmp += (acc_t)adj_matrix[i][j] * (acc_t)features[j][f];
            }

            // PO2 rescale: just a bit-shift with rounding
            acc_t rounded = tmp + round_const;
            acc_t result = rounded >> shift_amount;

            agg_out[i][f] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (i == 6 && f < 3) {
                printf("  AGG_PO2: node=%d feat=%d tmp=%d shift=%d result=%d out=%d\n",
                       i, f, (int)tmp, shift_amount, (int)result, (int)agg_out[i][f]);
            }
#endif
        }
    }
}

// ============================================================================
// PO2 Linear Transform (NO MULTIPLIER for scaling!)
// ============================================================================
/**
 * Integer-only linear with power-of-two rescaling.
 * 
 * Formula:
 *   acc = bias + sum_f(feat[n,f] * weight[o,f])
 *   result = (acc + rounding) >> shift
 */
template<int N_NODES, int IN_FEAT, int OUT_FEAT>
void linear_int8_po2(
    const data_t   features[N_NODES][IN_FEAT],
    const weight_t weights[OUT_FEAT][IN_FEAT],
    const bias_t   bias[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT],
    const int      shift_amount
) {
#pragma HLS INLINE

    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

LIN_N:
    for (int n = 0; n < N_NODES; n++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    LIN_O:
        for (int o = 0; o < OUT_FEAT; o++) {
#if DSE_UNROLL_OUTPUTS > 1
#pragma HLS UNROLL factor=DSE_UNROLL_OUTPUTS
#elif DSE_UNROLL_OUTPUTS == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_LIN_PIPELINE_II
#endif

            // Start with pre-scaled bias
            acc_t acc = bias[o];

        LIN_F:
            for (int f = 0; f < IN_FEAT; f++) {
#if DSE_UNROLL_FEATURES_LIN > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_LIN
#elif DSE_UNROLL_FEATURES_LIN == 0
#pragma HLS UNROLL
#endif
                // INT8 × INT8 → Configurable multiply binding
                acc_t prod;
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_LIN_MUL
#if DSE_ALLOC_LIN_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_LIN_MUL_LIMIT operation
#endif
                prod = (acc_t)features[n][f] * (acc_t)weights[o][f];
                acc += prod;
            }

            // PO2 rescale: just a bit-shift
            acc_t rounded = acc + round_const;
            acc_t result = rounded >> shift_amount;

            output[n][o] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (n == 6 && o < 3) {
                printf("  LIN_PO2: node=%d out=%d acc=%d shift=%d result=%d out=%d\n",
                       n, o, (int)acc, shift_amount, (int)result, (int)output[n][o]);
            }
#endif
        }
    }
}

// ============================================================================
// ReLU (same as INT8 version)
// ============================================================================

template<int N_NODES, int N_FEAT>
void relu_int8(data_t data[N_NODES][N_FEAT]) {
#pragma HLS INLINE

RELU_N:
    for (int n = 0; n < N_NODES; n++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    RELU_F:
        for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_RELU > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_RELU
#elif DSE_UNROLL_FEATURES_RELU == 0
#pragma HLS UNROLL
#endif
            if (data[n][f] < 0) {
                data[n][f] = 0;
            }
        }
    }
}

// ============================================================================
// Full Network - PO2 Version
// ============================================================================

template<int N_NODES, int IN_FEAT, int HIDDEN_FEAT, int OUT_FEAT>
void graphsage_int8_po2_template(
    const adj_t    adj_matrix[N_NODES][N_NODES],
    const data_t   input[N_NODES][IN_FEAT],
    const weight_t weights1[HIDDEN_FEAT][IN_FEAT],
    const bias_t   bias1[HIDDEN_FEAT],
    const weight_t weights2[OUT_FEAT][HIDDEN_FEAT],
    const bias_t   bias2[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT]
) {
    //#pragma HLS INLINE off
    // Intermediate buffers
    data_t agg1[N_NODES][IN_FEAT];
    data_t hidden[N_NODES][HIDDEN_FEAT];
    data_t agg2[N_NODES][HIDDEN_FEAT];

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 1 AGGREGATION (shift=%d) ===\n", BETA1_SHIFT);
#endif

    // Layer 1: Aggregate → Linear → ReLU
    aggregate_int8_po2<N_NODES, IN_FEAT>(
        adj_matrix, input, agg1, BETA1_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 1 LINEAR (shift=%d) ===\n", EFF_SCALE1_SHIFT);
#endif

    linear_int8_po2<N_NODES, IN_FEAT, HIDDEN_FEAT>(
        agg1, weights1, bias1, hidden, EFF_SCALE1_SHIFT
    );
    relu_int8<N_NODES, HIDDEN_FEAT>(hidden);

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 2 AGGREGATION (shift=%d) ===\n", BETA2_SHIFT);
#endif

    // Layer 2: Aggregate → Linear
    aggregate_int8_po2<N_NODES, HIDDEN_FEAT>(
        adj_matrix, hidden, agg2, BETA2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 2 LINEAR (shift=%d) ===\n", EFF_SCALE2_SHIFT);
#endif

    linear_int8_po2<N_NODES, HIDDEN_FEAT, OUT_FEAT>(
        agg2, weights2, bias2, output, EFF_SCALE2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS COMPLETE ===\n\n");
#endif
}

// ============================================================================
// Top-Level Wrapper
// ============================================================================

void graphsage_int8_po2(
    const adj_t    adj_matrix[NUM_NODES][NUM_NODES],
    const data_t   input[NUM_NODES][IN_FEATURES],
    const weight_t weights1[HIDDEN_FEATURES][IN_FEATURES],
    const bias_t   bias1[HIDDEN_FEATURES],
    const weight_t weights2[OUT_FEATURES][HIDDEN_FEATURES],
    const bias_t   bias2[OUT_FEATURES],
    data_t         output[NUM_NODES][OUT_FEATURES]
);
