/**
 * GraphSAGE Layer for FPGA - INT8 with POWER-OF-TWO SCALES
 * 
 * OPTIMIZED VERSION: PO2 scales + latency-preserving internal-locality experiment.
 *
 * LOCALITY MODE (default enabled):
 *   - No DATAFLOW
 *   - No intentional extra pipeline stage
 *   - AGG1 outputs are replicated at the producer boundary for LIN1 groups
 *   - LIN1+ReLU outputs are replicated at the producer boundary for AGG2 node groups
 *   - Designed to reduce long activation-register -> DSP routes
 * This eliminates the ~500-700 DSP48s used for scale multiplications.
 * 
 * Key differences from graphsage_layer_int8.h:
 *   - Scale values are constrained to powers of 2
 *   - Scale multiplication replaced with bit-shift
 *   - Shorter critical path → better timing
 *   - Lower DSP usage
 * 
 * Usage:
 *   1. Generate PO2 parameters: python prepare_ptq_int8_parameters.py --po2-scales
 *   2. Compile with: -DUSE_PO2_SCALES
 *   3. Optionally enable optimized bitwidths: -DUSE_OPTIMIZED_BITWIDTHS
 */

#pragma once

#include <stdint.h>
#include <ap_int.h>

#ifndef __SYNTHESIS__
#include <cstdio>
#endif

// ============================================================================
// OPTIMIZED BIT-WIDTHS SUPPORT
// ============================================================================
//
// To use auto-generated optimized bit-widths:
//   1. Run: cd src && python optimize_bitwidths_int8.py
//   2. Pass -DUSE_OPTIMIZED_BITWIDTHS to the compiler
//
// This will include auto_generated_bitwidths.h and use OPT_* values.

#ifdef USE_OPTIMIZED_BITWIDTHS
#include "auto_generated_bitwidths.h"
#endif

// ============================================================================
// Design Space Exploration Configuration
// ============================================================================
// Include DSE config if available (generated by explore_design_space.py)
#ifdef DSE_CONFIG
#include "dse_config.h"
#endif

// Default pragma parameters (used if DSE config not provided)
#ifndef DSE_UNROLL_NODES
#define DSE_UNROLL_NODES 0  // 0 = complete unroll
#endif

#ifndef DSE_UNROLL_FEATURES_AGG
#define DSE_UNROLL_FEATURES_AGG 0
#endif

#ifndef DSE_UNROLL_FEATURES_LIN
#define DSE_UNROLL_FEATURES_LIN 0
#endif

#ifndef DSE_UNROLL_FEATURES_RELU
#define DSE_UNROLL_FEATURES_RELU 0
#endif

#ifndef DSE_UNROLL_OUTPUTS
#define DSE_UNROLL_OUTPUTS 1  // 1 = pipeline (default), >1 = partial unroll, 0 = complete unroll
#endif

#ifndef DSE_AGG_PIPELINE_II
#define DSE_AGG_PIPELINE_II 1
#endif

#ifndef DSE_LIN_PIPELINE_II
#define DSE_LIN_PIPELINE_II 1
#endif

#ifndef DSE_BIND_AGG_MUL
#define DSE_BIND_AGG_MUL "dsp"  // "dsp" or "fabric"
#endif

#ifndef DSE_BIND_LIN_MUL
#define DSE_BIND_LIN_MUL "dsp"  // "dsp" or "fabric"
#endif

#ifndef DSE_LIN_MUL_LATENCY
#define DSE_LIN_MUL_LATENCY -1  // -1 = tool default
#endif

#ifndef DSE_TARGET_LATENCY
#define DSE_TARGET_LATENCY -1  // -1 = unconstrained
#endif


// ============================================================================
// Internal locality experiment
// ============================================================================
//
// Goal:
//   Preserve the latency-first architecture (II=1 / no intentional new
//   pipeline stage) while breaking global activation-to-DSP broadcast domains.
//
// DSE_ENABLE_INTERNAL_LOCALITY = 1:
//   - AGG1 produces multiple same-stage copies, one per LIN1 output group.
//   - LIN1 consumes those local copies and directly produces multiple ReLU'd
//     hidden copies, one per AGG2 destination-node group.
//   - AGG2 consumes the hidden copy associated with its destination-node group.
//   - No DATAFLOW is used.
//   - No extra copy loop exists as a separate pipeline stage.
//
// IMPORTANT:
//   HLS/Vivado must still be checked to confirm that the copies survive
//   synthesis as independent registers and that cycle latency/II are unchanged.
//
#ifndef DSE_ENABLE_INTERNAL_LOCALITY
#define DSE_ENABLE_INTERNAL_LOCALITY 1
#endif

// Layer-1 linear consumer domains.
// HIDDEN_FEATURES must be divisible by this value.
// Default: 24 outputs -> 4 groups of 6 outputs.
#ifndef DSE_LOCALITY_LIN1_GROUPS
#define DSE_LOCALITY_LIN1_GROUPS 4
#endif

// Layer-2 aggregation destination-node domains.
// NUM_NODES must be divisible by this value.
// Default: 8 destination nodes -> 4 groups of 2 nodes.
#ifndef DSE_LOCALITY_AGG2_GROUPS
#define DSE_LOCALITY_AGG2_GROUPS 4
#endif

#ifndef DSE_ALLOC_AGG_MUL_LIMIT
#define DSE_ALLOC_AGG_MUL_LIMIT -1  // -1 = unlimited
#endif

#ifndef DSE_ALLOC_LIN_MUL_LIMIT
#define DSE_ALLOC_LIN_MUL_LIMIT -1  // -1 = unlimited
#endif

// ============================================================================
// Configuration
// ============================================================================

// Map DSE configuration to standard names (if DSE config is provided)
#ifdef DSE_CONFIG
    #define NUM_NODES DSE_NUM_NODES
    #define IN_FEATURES DSE_IN_FEATURES
    #define HIDDEN_FEATURES DSE_HIDDEN_FEATURES
    #define OUT_FEATURES DSE_OUT_FEATURES
#else
    // Defaults when not using DSE
    #ifndef NUM_NODES
    #define NUM_NODES 8
    #endif

    #ifndef IN_FEATURES
    #define IN_FEATURES 16
    #endif

    #ifndef HIDDEN_FEATURES
    #define HIDDEN_FEATURES 24
    #endif

    #ifndef OUT_FEATURES
    #define OUT_FEATURES 7
    #endif
#endif

// Fixed-point configuration
#ifndef M_BITS
#define M_BITS 24  // Fractional bits for intermediate calculations
#endif

#ifndef K_BITS
#define K_BITS 12  // Adjacency scale: A_int = A_float * 2^12
#endif

// ============================================================================
// Power-of-Two Scale Shift Amounts
// ============================================================================
// 
// These replace arbitrary scale values with shift amounts.
// Formula: shift = M_BITS - log2(scale_po2)
//
// Example: If eff_scale_float = 0.0106867758
//          eff_scale_fp = 0.0106867758 * 2^24 = 179,294
//          Nearest PO2 = 2^17 = 131,072
//          Shift = 24 - 17 = 7
//
// Scale factors are model-dependent and should be provided via compiler flags (-D)
// when running DSE. The values below are defaults that may not match your model.
// DSE automatically loads shifts from build/test_vectors_ptq_int8_po2/po2_config.json

#ifndef EFF_SCALE1_SHIFT
#define EFF_SCALE1_SHIFT 7   // Default - override via -DEFF_SCALE1_SHIFT=X
#endif

#ifndef EFF_SCALE2_SHIFT
#define EFF_SCALE2_SHIFT 8   // Default - override via -DEFF_SCALE2_SHIFT=X
#endif

#ifndef BETA1_SHIFT
#define BETA1_SHIFT 17       // Default - override via -DBETA1_SHIFT=X
#endif

#ifndef BETA2_SHIFT
#define BETA2_SHIFT 12       // Corresponds to scale = 2^12 (exact!)
#endif

// ============================================================================
// Optimized Bit-Widths (from data-driven analysis or defaults)
// ============================================================================

#ifndef ADJ_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value
#define ADJ_BITS OPT_ADJ_BITS
#else
// Conservative default
#define ADJ_BITS 16          // Adjacency: 2^12 max → 13 bits + margin
#endif
#endif

#ifndef ACC_BITS
#ifdef USE_OPTIMIZED_BITWIDTHS
// Use data-driven optimized value (typically ~22 bits)
#define ACC_BITS OPT_ACC_BITS
#else
// Conservative default
#define ACC_BITS 22          // Accumulator: actual max ~389k → 19 bits + margin
#endif
#endif

// ============================================================================
// Type Definitions
// ============================================================================

typedef ap_int<8>        data_t;      // INT8 activations/weights
typedef ap_int<8>        weight_t;    // INT8 weights
typedef ap_int<ADJ_BITS> adj_t;       // Scaled adjacency matrix
typedef ap_int<ACC_BITS> acc_t;       // Accumulator
typedef ap_int<ACC_BITS> bias_t;      // Bias in accumulator domain
typedef ap_int<16>       lin_prod_t;  // INT8 x INT8 product
typedef ap_int<ADJ_BITS + 8> agg_prod_t; // Adjacency x INT8 product

// ============================================================================
// Helper: Clamp to INT8 range
// ============================================================================

inline data_t int8_clamp(acc_t x) {
#pragma HLS INLINE
    if (x > 127)  return data_t(127);
    if (x < -128) return data_t(-128);
    return data_t(x);
}


// Layer-1 linear output is immediately followed by ReLU in the original
// network.  clamp(INT8) + ReLU is exactly equivalent to clamp([0, 127]).
// Keeping this at the producer allows the local hidden copies to be written
// directly, avoiding a shared hidden register followed by replica registers.
inline data_t int8_relu_clamp(acc_t x) {
#pragma HLS INLINE
    if (x > 127) return data_t(127);
    if (x < 0)   return data_t(0);
    return data_t(x);
}

// ============================================================================
// PO2 Aggregation (NO MULTIPLIER for scaling!)
// ============================================================================
/**
 * Integer-only aggregation with power-of-two rescaling.
 * 
 * Formula:
 *   tmp = sum_j(adj[i,j] * feat[j,f])
 *   result = (tmp + rounding) >> shift
 * 
 * The shift replaces: (tmp * beta_fp + 2^(M-1)) >> M
 *                  =  (tmp * 2^S + 2^(M-1)) >> M
 *                  =  (tmp + 2^(M-S-1)) >> (M-S)
 *                  =  (tmp + 2^(shift-1)) >> shift
 */
template<int N_NODES, int N_FEAT>
void aggregate_int8_po2(
    const adj_t  adj_matrix[N_NODES][N_NODES],
    const data_t features[N_NODES][N_FEAT],
    data_t       agg_out[N_NODES][N_FEAT],
    const int    shift_amount
) {
#pragma HLS INLINE

    // Pre-compute rounding constant
    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

AGG_I:
    for (int i = 0; i < N_NODES; i++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    AGG_F:
        for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_AGG > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_AGG
#elif DSE_UNROLL_FEATURES_AGG == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_AGG_PIPELINE_II
#endif

            acc_t tmp = 0;

        AGG_J:
            for (int j = 0; j < N_NODES; j++) {
#pragma HLS UNROLL
                agg_prod_t prod;
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_AGG_MUL
                // Exact-width product is sign-extended into the accumulator.
#if DSE_ALLOC_AGG_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_AGG_MUL_LIMIT operation
#endif
                prod = adj_matrix[i][j] * features[j][f];
                tmp += (acc_t)prod;
            }

            // PO2 rescale: just a bit-shift with rounding
            acc_t rounded = tmp + round_const;
            acc_t result = rounded >> shift_amount;

            agg_out[i][f] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (i == 6 && f < 3) {
                printf("  AGG_PO2: node=%d feat=%d tmp=%d shift=%d result=%d out=%d\n",
                       i, f, (int)tmp, shift_amount, (int)result, (int)agg_out[i][f]);
            }
#endif
        }
    }
}

// ============================================================================
// PO2 Linear Transform (NO MULTIPLIER for scaling!)
// ============================================================================
/**
 * Integer-only linear with power-of-two rescaling.
 * 
 * Formula:
 *   acc = bias + sum_f(feat[n,f] * weight[o,f])
 *   result = (acc + rounding) >> shift
 */
template<int N_NODES, int IN_FEAT, int OUT_FEAT>
void linear_int8_po2(
    const data_t   features[N_NODES][IN_FEAT],
    const weight_t weights[OUT_FEAT][IN_FEAT],
    const bias_t   bias[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT],
    const int      shift_amount
) {
#pragma HLS INLINE

    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

LIN_N:
    for (int n = 0; n < N_NODES; n++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    LIN_O:
        for (int o = 0; o < OUT_FEAT; o++) {
#if DSE_UNROLL_OUTPUTS > 1
#pragma HLS UNROLL factor=DSE_UNROLL_OUTPUTS
#elif DSE_UNROLL_OUTPUTS == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_LIN_PIPELINE_II
#endif

            // Start with pre-scaled bias
            acc_t acc = bias[o];

        LIN_F:
            for (int f = 0; f < IN_FEAT; f++) {
#if DSE_UNROLL_FEATURES_LIN > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_LIN
#elif DSE_UNROLL_FEATURES_LIN == 0
#pragma HLS UNROLL
#endif
                // INT8 × INT8 → Configurable multiply binding
                lin_prod_t prod;
#if DSE_LIN_MUL_LATENCY >= 0
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_LIN_MUL latency=DSE_LIN_MUL_LATENCY
#else
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_LIN_MUL
#endif
#if DSE_ALLOC_LIN_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_LIN_MUL_LIMIT operation
#endif
                prod = features[n][f] * weights[o][f];
                acc += (acc_t)prod;
            }

            // PO2 rescale: just a bit-shift
            acc_t rounded = acc + round_const;
            acc_t result = rounded >> shift_amount;

            output[n][o] = int8_clamp(result);

#ifndef __SYNTHESIS__
            if (n == 6 && o < 3) {
                printf("  LIN_PO2: node=%d out=%d acc=%d shift=%d result=%d out=%d\n",
                       n, o, (int)acc, shift_amount, (int)result, (int)output[n][o]);
            }
#endif
        }
    }
}


// ============================================================================
// INTERNAL-LOCALITY KERNELS (NO DATAFLOW)
// ============================================================================

// ----------------------------------------------------------------------------
// AGGREGATION WITH SAME-STAGE REPLICATED OUTPUTS
// ----------------------------------------------------------------------------
//
// The arithmetic is computed once, but the quantized result is written directly
// to N_COPIES independent array elements at the producer boundary.
//
// This is intentionally different from:
//
//     shared_reg -> replica_reg[0..N]
//
// because there is no explicit post-producer copy stage in the C++.
//
// The generated RTL MUST be inspected to verify that HLS/Vivado does not merge
// these copies back into a single shared register.
//
template<int N_NODES, int N_FEAT, int N_COPIES>
void aggregate_int8_po2_replicated(
    const adj_t  adj_matrix[N_NODES][N_NODES],
    const data_t features[N_NODES][N_FEAT],
    data_t       agg_out[N_COPIES][N_NODES][N_FEAT],
    const int    shift_amount
) {
#pragma HLS INLINE
#pragma HLS ARRAY_PARTITION variable=agg_out complete dim=1
#pragma HLS ARRAY_PARTITION variable=agg_out complete dim=2
#pragma HLS ARRAY_PARTITION variable=agg_out complete dim=3

    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

LOC_AGG_I:
    for (int i = 0; i < N_NODES; i++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif

    LOC_AGG_F:
        for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_AGG > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_AGG
#elif DSE_UNROLL_FEATURES_AGG == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_AGG_PIPELINE_II
#endif

            acc_t tmp = 0;

        LOC_AGG_J:
            for (int j = 0; j < N_NODES; j++) {
#pragma HLS UNROLL
                agg_prod_t prod;
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_AGG_MUL
#if DSE_ALLOC_AGG_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_AGG_MUL_LIMIT operation
#endif
                prod = adj_matrix[i][j] * features[j][f];
                tmp += (acc_t)prod;
            }

            const acc_t rounded = tmp + round_const;
            const acc_t result  = rounded >> shift_amount;

        LOC_AGG_COPY:
            for (int c = 0; c < N_COPIES; c++) {
#pragma HLS UNROLL
                // Keep the write at the producer boundary.  There is no
                // explicit shared agg_out register followed by copy registers.
                agg_out[c][i][f] = int8_clamp(result);
            }
        }
    }
}


// ----------------------------------------------------------------------------
// GROUPED LINEAR-1 + RELU WITH SAME-STAGE HIDDEN COPIES
// ----------------------------------------------------------------------------
//
// Each output-feature group consumes a different AGG1 copy:
//
//   agg_copy[0] -> outputs 0 .. group_size-1
//   agg_copy[1] -> next output group
//   ...
//
// The computed LIN1 result is ReLU-clamped and written directly to each AGG2
// locality copy.  This avoids:
//
//   hidden_shared_reg -> hidden_replica_reg -> AGG2 DSP
//
// All groups remain concurrent.  There is no DATAFLOW and no intentional new
// pipeline stage.
//
template<
    int N_NODES,
    int IN_FEAT,
    int OUT_FEAT,
    int IN_GROUPS,
    int OUT_COPIES
>
void linear_int8_po2_grouped_relu_replicated(
    const data_t   features[IN_GROUPS][N_NODES][IN_FEAT],
    const weight_t weights[OUT_FEAT][IN_FEAT],
    const bias_t   bias[OUT_FEAT],
    data_t         output[OUT_COPIES][N_NODES][OUT_FEAT],
    const int      shift_amount
) {
#pragma HLS INLINE
#pragma HLS ARRAY_PARTITION variable=features complete dim=1
#pragma HLS ARRAY_PARTITION variable=features complete dim=2
#pragma HLS ARRAY_PARTITION variable=features complete dim=3
#pragma HLS ARRAY_PARTITION variable=output complete dim=1
#pragma HLS ARRAY_PARTITION variable=output complete dim=2
#pragma HLS ARRAY_PARTITION variable=output complete dim=3

    static_assert(IN_GROUPS > 0, "IN_GROUPS must be > 0");
    static_assert(OUT_COPIES > 0, "OUT_COPIES must be > 0");
    static_assert(
        (OUT_FEAT % IN_GROUPS) == 0,
        "OUT_FEAT must be divisible by IN_GROUPS"
    );

    constexpr int OUTS_PER_GROUP = OUT_FEAT / IN_GROUPS;
    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

LOC_LIN_G:
    for (int g = 0; g < IN_GROUPS; g++) {
#pragma HLS UNROLL

    LOC_LIN_N:
        for (int n = 0; n < N_NODES; n++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif

        LOC_LIN_O:
            for (int oo = 0; oo < OUTS_PER_GROUP; oo++) {
#if DSE_UNROLL_OUTPUTS > 1
#pragma HLS UNROLL factor=DSE_UNROLL_OUTPUTS
#elif DSE_UNROLL_OUTPUTS == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_LIN_PIPELINE_II
#endif
                const int o = g * OUTS_PER_GROUP + oo;
                acc_t acc = bias[o];

            LOC_LIN_F:
                for (int f = 0; f < IN_FEAT; f++) {
#if DSE_UNROLL_FEATURES_LIN > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_LIN
#elif DSE_UNROLL_FEATURES_LIN == 0
#pragma HLS UNROLL
#endif
                    lin_prod_t prod;
#if DSE_LIN_MUL_LATENCY >= 0
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_LIN_MUL latency=DSE_LIN_MUL_LATENCY
#else
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_LIN_MUL
#endif
#if DSE_ALLOC_LIN_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_LIN_MUL_LIMIT operation
#endif
                    prod = features[g][n][f] * weights[o][f];
                    acc += (acc_t)prod;
                }

                const acc_t rounded = acc + round_const;
                const acc_t result  = rounded >> shift_amount;

            LOC_HIDDEN_COPY:
                for (int c = 0; c < OUT_COPIES; c++) {
#pragma HLS UNROLL
                    // Equivalent to original INT8 clamp followed by ReLU.
                    // Copy is made directly at the LIN1 producer boundary.
                    output[c][n][o] = int8_relu_clamp(result);
                }
            }
        }
    }
}


// ----------------------------------------------------------------------------
// AGGREGATION FROM DESTINATION-NODE-LOCAL FEATURE COPIES
// ----------------------------------------------------------------------------
//
// Each destination-node group consumes only its own hidden copy.  With
// NUM_NODES=8 and IN_GROUPS=4:
//
//   hidden_copy[0] -> destination nodes 0,1
//   hidden_copy[1] -> destination nodes 2,3
//   hidden_copy[2] -> destination nodes 4,5
//   hidden_copy[3] -> destination nodes 6,7
//
// This directly attacks the observed hidden_* -> DSP fanout-8 / cross-SLR
// paths without serializing the aggregation.
//
template<int N_NODES, int N_FEAT, int IN_GROUPS>
void aggregate_int8_po2_grouped_input(
    const adj_t  adj_matrix[N_NODES][N_NODES],
    const data_t features[IN_GROUPS][N_NODES][N_FEAT],
    data_t       agg_out[N_NODES][N_FEAT],
    const int    shift_amount
) {
#pragma HLS INLINE
#pragma HLS ARRAY_PARTITION variable=features complete dim=1
#pragma HLS ARRAY_PARTITION variable=features complete dim=2
#pragma HLS ARRAY_PARTITION variable=features complete dim=3

    static_assert(IN_GROUPS > 0, "IN_GROUPS must be > 0");
    static_assert(
        (N_NODES % IN_GROUPS) == 0,
        "N_NODES must be divisible by IN_GROUPS"
    );

    constexpr int NODES_PER_GROUP = N_NODES / IN_GROUPS;
    const acc_t round_const = (acc_t)(1) << (shift_amount - 1);

LOC_AGG2_G:
    for (int g = 0; g < IN_GROUPS; g++) {
#pragma HLS UNROLL

    LOC_AGG2_I:
        for (int ii = 0; ii < NODES_PER_GROUP; ii++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
            const int i = g * NODES_PER_GROUP + ii;

        LOC_AGG2_F:
            for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_AGG > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_AGG
#elif DSE_UNROLL_FEATURES_AGG == 0
#pragma HLS UNROLL
#else
#pragma HLS PIPELINE II=DSE_AGG_PIPELINE_II
#endif
                acc_t tmp = 0;

            LOC_AGG2_J:
                for (int j = 0; j < N_NODES; j++) {
#pragma HLS UNROLL
                    agg_prod_t prod;
#pragma HLS BIND_OP variable=prod op=mul impl=DSE_BIND_AGG_MUL
#if DSE_ALLOC_AGG_MUL_LIMIT > 0
#pragma HLS allocation instances=mul limit=DSE_ALLOC_AGG_MUL_LIMIT operation
#endif
                    // IMPORTANT: group-local hidden copy selected by the
                    // destination-node domain g.
                    prod = adj_matrix[i][j] * features[g][j][f];
                    tmp += (acc_t)prod;
                }

                const acc_t rounded = tmp + round_const;
                const acc_t result  = rounded >> shift_amount;
                agg_out[i][f] = int8_clamp(result);
            }
        }
    }
}


// ============================================================================
// ReLU (same as INT8 version)
// ============================================================================

template<int N_NODES, int N_FEAT>
void relu_int8(data_t data[N_NODES][N_FEAT]) {
#pragma HLS INLINE

RELU_N:
    for (int n = 0; n < N_NODES; n++) {
#if DSE_UNROLL_NODES > 1
#pragma HLS UNROLL factor=DSE_UNROLL_NODES
#elif DSE_UNROLL_NODES == 0
#pragma HLS UNROLL
#endif
    RELU_F:
        for (int f = 0; f < N_FEAT; f++) {
#if DSE_UNROLL_FEATURES_RELU > 1
#pragma HLS UNROLL factor=DSE_UNROLL_FEATURES_RELU
#elif DSE_UNROLL_FEATURES_RELU == 0
#pragma HLS UNROLL
#endif
            if (data[n][f] < 0) {
                data[n][f] = 0;
            }
        }
    }
}

// ============================================================================
// Full Network - PO2 Version
// ============================================================================

template<int N_NODES, int IN_FEAT, int HIDDEN_FEAT, int OUT_FEAT>
void graphsage_int8_po2_template(
    const adj_t    adj_matrix[N_NODES][N_NODES],
    const data_t   input[N_NODES][IN_FEAT],
    const weight_t weights1[HIDDEN_FEAT][IN_FEAT],
    const bias_t   bias1[HIDDEN_FEAT],
    const weight_t weights2[OUT_FEAT][HIDDEN_FEAT],
    const bias_t   bias2[OUT_FEAT],
    data_t         output[N_NODES][OUT_FEAT]
) {
#if DSE_ENABLE_INTERNAL_LOCALITY

    // ------------------------------------------------------------------------
    // Locality-first implementation
    // ------------------------------------------------------------------------
    //
    // Hard constraints for the default configuration:
    //   HIDDEN_FEAT=24, LIN1_GROUPS=4  -> 6 output features per LIN1 group
    //   N_NODES=8,   AGG2_GROUPS=4    -> 2 destination nodes per AGG2 group
    //
    // The copies are produced directly at the existing producer boundaries.
    // There is intentionally NO DATAFLOW and NO explicit extra copy stage.
    //
    static_assert(
        (HIDDEN_FEAT % DSE_LOCALITY_LIN1_GROUPS) == 0,
        "HIDDEN_FEAT must be divisible by DSE_LOCALITY_LIN1_GROUPS"
    );
    static_assert(
        (N_NODES % DSE_LOCALITY_AGG2_GROUPS) == 0,
        "N_NODES must be divisible by DSE_LOCALITY_AGG2_GROUPS"
    );

    data_t agg1_local
        [DSE_LOCALITY_LIN1_GROUPS]
        [N_NODES]
        [IN_FEAT];

    data_t hidden_local
        [DSE_LOCALITY_AGG2_GROUPS]
        [N_NODES]
        [HIDDEN_FEAT];

    data_t agg2[N_NODES][HIDDEN_FEAT];

    // Make the locality dimensions physically explicit as independent scalar
    // registers rather than inferred memories/muxed storage.
#pragma HLS ARRAY_PARTITION variable=agg1_local complete dim=1
#pragma HLS ARRAY_PARTITION variable=agg1_local complete dim=2
#pragma HLS ARRAY_PARTITION variable=agg1_local complete dim=3

#pragma HLS ARRAY_PARTITION variable=hidden_local complete dim=1
#pragma HLS ARRAY_PARTITION variable=hidden_local complete dim=2
#pragma HLS ARRAY_PARTITION variable=hidden_local complete dim=3

#pragma HLS ARRAY_PARTITION variable=agg2 complete dim=1
#pragma HLS ARRAY_PARTITION variable=agg2 complete dim=2

#ifndef __SYNTHESIS__
    printf(
        "\n=== INT8-PO2 HLS LOCALITY: LAYER 1 AGGREGATION "
        "(copies=%d, shift=%d) ===\n",
        DSE_LOCALITY_LIN1_GROUPS,
        BETA1_SHIFT
    );
#endif

    // Layer 1 aggregation writes directly into one local activation copy per
    // LIN1 output-feature domain.
    aggregate_int8_po2_replicated<
        N_NODES,
        IN_FEAT,
        DSE_LOCALITY_LIN1_GROUPS
    >(
        adj_matrix,
        input,
        agg1_local,
        BETA1_SHIFT
    );

#ifndef __SYNTHESIS__
    printf(
        "\n=== INT8-PO2 HLS LOCALITY: LAYER 1 LINEAR+RELU "
        "(input_groups=%d, hidden_copies=%d, shift=%d) ===\n",
        DSE_LOCALITY_LIN1_GROUPS,
        DSE_LOCALITY_AGG2_GROUPS,
        EFF_SCALE1_SHIFT
    );
#endif

    // Each LIN1 output group consumes only its matching agg1 copy.
    // The ReLU'd result is written directly into the AGG2 node-domain copies.
    linear_int8_po2_grouped_relu_replicated<
        N_NODES,
        IN_FEAT,
        HIDDEN_FEAT,
        DSE_LOCALITY_LIN1_GROUPS,
        DSE_LOCALITY_AGG2_GROUPS
    >(
        agg1_local,
        weights1,
        bias1,
        hidden_local,
        EFF_SCALE1_SHIFT
    );

#ifndef __SYNTHESIS__
    printf(
        "\n=== INT8-PO2 HLS LOCALITY: LAYER 2 AGGREGATION "
        "(node_groups=%d, shift=%d) ===\n",
        DSE_LOCALITY_AGG2_GROUPS,
        BETA2_SHIFT
    );
#endif

    // Each destination-node group reads only its own hidden copy.
    aggregate_int8_po2_grouped_input<
        N_NODES,
        HIDDEN_FEAT,
        DSE_LOCALITY_AGG2_GROUPS
    >(
        adj_matrix,
        hidden_local,
        agg2,
        BETA2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf(
        "\n=== INT8-PO2 HLS LOCALITY: LAYER 2 LINEAR "
        "(shift=%d) ===\n",
        EFF_SCALE2_SHIFT
    );
#endif

    // Final layer remains unchanged for this first locality experiment.
    linear_int8_po2<N_NODES, HIDDEN_FEAT, OUT_FEAT>(
        agg2,
        weights2,
        bias2,
        output,
        EFF_SCALE2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS LOCALITY COMPLETE ===\n\n");
#endif

#else

    // ------------------------------------------------------------------------
    // Original implementation (A/B reference)
    // ------------------------------------------------------------------------
    data_t agg1[N_NODES][IN_FEAT];
    data_t hidden[N_NODES][HIDDEN_FEAT];
    data_t agg2[N_NODES][HIDDEN_FEAT];

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 1 AGGREGATION (shift=%d) ===\n", BETA1_SHIFT);
#endif

    aggregate_int8_po2<N_NODES, IN_FEAT>(
        adj_matrix, input, agg1, BETA1_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 1 LINEAR (shift=%d) ===\n", EFF_SCALE1_SHIFT);
#endif

    linear_int8_po2<N_NODES, IN_FEAT, HIDDEN_FEAT>(
        agg1, weights1, bias1, hidden, EFF_SCALE1_SHIFT
    );
    relu_int8<N_NODES, HIDDEN_FEAT>(hidden);

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 2 AGGREGATION (shift=%d) ===\n", BETA2_SHIFT);
#endif

    aggregate_int8_po2<N_NODES, HIDDEN_FEAT>(
        adj_matrix, hidden, agg2, BETA2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS: LAYER 2 LINEAR (shift=%d) ===\n", EFF_SCALE2_SHIFT);
#endif

    linear_int8_po2<N_NODES, HIDDEN_FEAT, OUT_FEAT>(
        agg2, weights2, bias2, output, EFF_SCALE2_SHIFT
    );

#ifndef __SYNTHESIS__
    printf("\n=== INT8-PO2 HLS COMPLETE ===\n\n");
#endif

#endif
}

// ============================================================================
// Top-Level Wrapper
// ============================================================================

void graphsage_int8_po2(
    const adj_t    adj_matrix[NUM_NODES][NUM_NODES],
    const data_t   input[NUM_NODES][IN_FEATURES],
    const weight_t weights1[HIDDEN_FEATURES][IN_FEATURES],
    const bias_t   bias1[HIDDEN_FEATURES],
    const weight_t weights2[OUT_FEATURES][HIDDEN_FEATURES],
    const bias_t   bias2[OUT_FEATURES],
    data_t         output[NUM_NODES][OUT_FEATURES]
);
