# csim.tcl — generated by HLS-auto. DO NOT EDIT BY HAND.
puts "=========================================="
puts "  C SIMULATION - graphsage_int8_po2"
puts "=========================================="
puts ""

# Absolute path to this module's HLS project directory
set project_dir "/home/pelayo/work/simple-gnn/build/hls/graphsage_int8_po2"
puts "▶ Opening project: $project_dir"
open_project $project_dir

puts "▶ Opening solution: solution1"
open_solution "solution1"

# User-provided (or auto-augmented) csim flags
#   e.g. "-clean -ldflags -lpugixml"
set csim_opts "-clean"

# Runtime arguments passed to the C++ testbench main(), like:
#   "--backend csim --event 17 --log /abs/.../logs /abs/.../omtf_events_full.xml"
set tb_args ""

# Build the full csim_design option string
if { $tb_args ne "" } {
    if { $csim_opts eq "" } {
        set full_opts "-argv {$tb_args}"
    } else {
        set full_opts "$csim_opts -argv {$tb_args}"
    }
} else {
    set full_opts $csim_opts
}

puts ""
puts "=========================================="
puts "  STARTING C SIMULATION"
puts "=========================================="

if { $full_opts eq "" } {
    puts "▶ Command: csim_design (default opts)"
    set status [catch {csim_design} errMsg]
} else {
    puts "▶ Command: csim_design $full_opts"
    set status [catch {eval csim_design $full_opts} errMsg]
}
puts ""

if {$status != 0} {
    puts "=========================================="
    puts "  ❌ C-SIMULATION FAILED"
    puts "=========================================="
    puts "Error: $errMsg"
    exit 1
} else {
    puts "=========================================="
    puts "  ✅ C-SIMULATION PASS"
    puts "=========================================="
}

close_project
exit