#!/usr/bin/env python3
"""Generate the Section-15 integrated wrapper (BUFG -> input registers ->
accelerator -> output registers) by parsing the ACTUAL top-level Verilog
port declaration from a completed HLS synthesis, rather than guessing port
names/widths by hand. Run this only after a csynth run for the target
variant has produced solution1/syn/verilog/<top>.v.

Usage:
  generate_wrapper.py <path-to-top-level-verilog> --top graphsage_po2_qat_partitioned
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_ports(verilog_path: Path, top: str) -> list[tuple[str, str, int, int]]:
    """Returns list of (direction, name, msb, lsb). Width 1 signals get msb=lsb=0."""
    text = verilog_path.read_text()
    # Vitis HLS emits one of two header styles; handle the common
    # `module top (\n ... );` with per-port `input`/`output` declarations
    # inside the parameter-less header, OR ANSI-style with input/output in
    # the port list itself. Parse declarations, not just the port list,
    # since HLS commonly uses the older Verilog-2001 non-ANSI style.
    module_match = re.search(rf"module\s+{re.escape(top)}\s*\((.*?)\);", text, re.DOTALL)
    if not module_match:
        raise ValueError(f"Could not find 'module {top} (...);' header in {verilog_path}")
    header_end = module_match.end()
    # Declarations for non-ANSI style appear after the header, before the
    # first 'wire'/'reg'/always/assign that isn't itself a port decl.
    body = text[header_end:]
    ports = []
    decl_re = re.compile(
        r"^\s*(input|output)\s+(?:wire\s+|reg\s+)?(?:\[(\d+):(\d+)\]\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*;",
        re.MULTILINE,
    )
    seen = set()
    for m in decl_re.finditer(body):
        direction, msb, lsb, name = m.groups()
        if name in seen:
            continue
        seen.add(name)
        ports.append((direction, name, int(msb) if msb else 0, int(lsb) if lsb else 0))
        if len(seen) > 500:
            break
    if not ports:
        raise ValueError(f"No input/output declarations parsed after module header in {verilog_path}")
    return ports


def classify(name: str) -> str:
    if name == "ap_clk":
        return "clock"
    if name in ("ap_rst", "ap_rst_n", "ap_rstn", "rst", "rstn"):
        return "reset"
    if name.startswith("input_"):
        return "data_in"
    if name.startswith("edge_masks"):
        return "data_in"
    if name.startswith("output_"):
        return "data_out"
    return "other"


def emit_wrapper(ports: list[tuple[str, str, int, int]], top: str, wrapper_name: str) -> str:
    inputs = [(n, msb, lsb) for d, n, msb, lsb in ports if d == "input"]
    outputs = [(n, msb, lsb) for d, n, msb, lsb in ports if d == "output"]

    clock_ports = [n for n, *_ in inputs if classify(n) == "clock"]
    reset_ports = [n for n, *_ in inputs if classify(n) == "reset"]
    data_in = [(n, msb, lsb) for n, msb, lsb in inputs if classify(n) == "data_in"]
    data_out = [(n, msb, lsb) for n, msb, lsb in outputs if classify(n) == "data_out"]
    other_in = [(n, msb, lsb) for n, msb, lsb in inputs if classify(n) == "other"]
    other_out = [(n, msb, lsb) for n, msb, lsb in outputs if classify(n) == "other"]
    if other_in or other_out:
        raise ValueError(f"Unclassified ports found, inspect manually: in={other_in} out={other_out}")
    if len(clock_ports) != 1:
        raise ValueError(f"Expected exactly one clock port, found {clock_ports}")
    clk = clock_ports[0]
    rst = reset_ports[0] if reset_ports else None

    def width(msb: int, lsb: int) -> int:
        return msb - lsb + 1

    lines = []
    lines.append(f"// Auto-generated by generate_wrapper.py from the actual {top} RTL port list.")
    lines.append("// Plan Section 15: clock input -> BUFG -> input registers -> accelerator -> output registers.")
    lines.append(f"module {wrapper_name} (")
    lines.append("    input  wire clk_in,")
    if rst:
        lines.append("    input  wire rst_in,")
    for n, msb, lsb in data_in:
        w = width(msb, lsb)
        bus = f"[{msb}:{lsb}] " if w > 1 else ""
        lines.append(f"    input  wire {bus}wrap_{n},")
    for i, (n, msb, lsb) in enumerate(data_out):
        w = width(msb, lsb)
        bus = f"[{msb}:{lsb}] " if w > 1 else ""
        comma = "," if i < len(data_out) - 1 else ""
        lines.append(f"    output wire {bus}wrap_{n}{comma}")
    lines.append(");")
    lines.append("")
    lines.append("    wire ap_clk_buf;")
    lines.append("    BUFG bufg_ap_clk (.I(clk_in), .O(ap_clk_buf));")
    lines.append("")
    if rst:
        lines.append("    reg rst_reg;")
        lines.append("    always @(posedge ap_clk_buf) rst_reg <= rst_in;")
        lines.append("")
    for n, msb, lsb in data_in:
        w = width(msb, lsb)
        bus = f"[{msb}:{lsb}] " if w > 1 else ""
        lines.append(f"    reg {bus}{n}_reg;")
    lines.append("    always @(posedge ap_clk_buf) begin")
    for n, _, _ in data_in:
        lines.append(f"        {n}_reg <= wrap_{n};")
    lines.append("    end")
    lines.append("")
    for n, msb, lsb in data_out:
        w = width(msb, lsb)
        bus = f"[{msb}:{lsb}] " if w > 1 else ""
        lines.append(f"    reg {bus}{n}_reg;")
    lines_out_wires = []
    for n, msb, lsb in data_out:
        w = width(msb, lsb)
        bus = f"[{msb}:{lsb}] " if w > 1 else ""
        lines_out_wires.append(f"    wire {bus}{n}_comb;")
    lines.extend(lines_out_wires)
    lines.append("    always @(posedge ap_clk_buf) begin")
    for n, _, _ in data_out:
        lines.append(f"        {n}_reg <= {n}_comb;")
    lines.append("    end")
    for n, _, _ in data_out:
        lines.append(f"    assign wrap_{n} = {n}_reg;")
    lines.append("")
    lines.append(f"    {top} u_accel (")
    lines.append(f"        .ap_clk({'ap_clk_buf'}),")
    if rst:
        lines.append(f"        .{rst}(rst_reg),")
    accel_ports = []
    for n, _, _ in data_in:
        accel_ports.append(f"        .{n}({n}_reg)")
    for n, _, _ in data_out:
        accel_ports.append(f"        .{n}({n}_comb)")
    lines.append(",\n".join(accel_ports))
    lines.append("    );")
    lines.append("")
    lines.append("endmodule")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("verilog_path", type=Path)
    parser.add_argument("--top", default="graphsage_po2_qat_partitioned")
    parser.add_argument("--wrapper-name", default="graphsage_integrated_wrapper")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    ports = parse_ports(args.verilog_path, args.top)
    print(f"Parsed {len(ports)} ports:")
    for d, n, msb, lsb in ports:
        print(f"  {d:6s} {n} [{msb}:{lsb}]")

    rtl = emit_wrapper(ports, args.top, args.wrapper_name)
    out = args.out or (args.verilog_path.parent / f"{args.wrapper_name}.v")
    out.write_text(rtl + "\n")
    print(f"WROTE={out}")


if __name__ == "__main__":
    main()
