// Auto-generated by generate_wrapper.py from the actual graphsage_po2_qat_partitioned RTL port list.
// Plan Section 15: clock input -> BUFG -> input registers -> accelerator -> output registers.
module graphsage_integrated_wrapper (
    input  wire clk_in,
    input  wire rst_in,
    input  wire [7:0] wrap_input_0_0,
    input  wire [7:0] wrap_input_0_1,
    input  wire [7:0] wrap_input_0_2,
    input  wire [7:0] wrap_input_0_3,
    input  wire [7:0] wrap_input_0_4,
    input  wire [7:0] wrap_input_0_5,
    input  wire [7:0] wrap_input_0_6,
    input  wire [7:0] wrap_input_0_7,
    input  wire [7:0] wrap_input_0_8,
    input  wire [7:0] wrap_input_0_9,
    input  wire [7:0] wrap_input_0_10,
    input  wire [7:0] wrap_input_0_11,
    input  wire [7:0] wrap_input_0_12,
    input  wire [7:0] wrap_input_0_13,
    input  wire [7:0] wrap_input_0_14,
    input  wire [7:0] wrap_input_0_15,
    input  wire [7:0] wrap_input_1_0,
    input  wire [7:0] wrap_input_1_1,
    input  wire [7:0] wrap_input_1_2,
    input  wire [7:0] wrap_input_1_3,
    input  wire [7:0] wrap_input_1_4,
    input  wire [7:0] wrap_input_1_5,
    input  wire [7:0] wrap_input_1_6,
    input  wire [7:0] wrap_input_1_7,
    input  wire [7:0] wrap_input_1_8,
    input  wire [7:0] wrap_input_1_9,
    input  wire [7:0] wrap_input_1_10,
    input  wire [7:0] wrap_input_1_11,
    input  wire [7:0] wrap_input_1_12,
    input  wire [7:0] wrap_input_1_13,
    input  wire [7:0] wrap_input_1_14,
    input  wire [7:0] wrap_input_1_15,
    input  wire [7:0] wrap_input_2_0,
    input  wire [7:0] wrap_input_2_1,
    input  wire [7:0] wrap_input_2_2,
    input  wire [7:0] wrap_input_2_3,
    input  wire [7:0] wrap_input_2_4,
    input  wire [7:0] wrap_input_2_5,
    input  wire [7:0] wrap_input_2_6,
    input  wire [7:0] wrap_input_2_7,
    input  wire [7:0] wrap_input_2_8,
    input  wire [7:0] wrap_input_2_9,
    input  wire [7:0] wrap_input_2_10,
    input  wire [7:0] wrap_input_2_11,
    input  wire [7:0] wrap_input_2_12,
    input  wire [7:0] wrap_input_2_13,
    input  wire [7:0] wrap_input_2_14,
    input  wire [7:0] wrap_input_2_15,
    input  wire [7:0] wrap_input_3_0,
    input  wire [7:0] wrap_input_3_1,
    input  wire [7:0] wrap_input_3_2,
    input  wire [7:0] wrap_input_3_3,
    input  wire [7:0] wrap_input_3_4,
    input  wire [7:0] wrap_input_3_5,
    input  wire [7:0] wrap_input_3_6,
    input  wire [7:0] wrap_input_3_7,
    input  wire [7:0] wrap_input_3_8,
    input  wire [7:0] wrap_input_3_9,
    input  wire [7:0] wrap_input_3_10,
    input  wire [7:0] wrap_input_3_11,
    input  wire [7:0] wrap_input_3_12,
    input  wire [7:0] wrap_input_3_13,
    input  wire [7:0] wrap_input_3_14,
    input  wire [7:0] wrap_input_3_15,
    input  wire [7:0] wrap_input_4_0,
    input  wire [7:0] wrap_input_4_1,
    input  wire [7:0] wrap_input_4_2,
    input  wire [7:0] wrap_input_4_3,
    input  wire [7:0] wrap_input_4_4,
    input  wire [7:0] wrap_input_4_5,
    input  wire [7:0] wrap_input_4_6,
    input  wire [7:0] wrap_input_4_7,
    input  wire [7:0] wrap_input_4_8,
    input  wire [7:0] wrap_input_4_9,
    input  wire [7:0] wrap_input_4_10,
    input  wire [7:0] wrap_input_4_11,
    input  wire [7:0] wrap_input_4_12,
    input  wire [7:0] wrap_input_4_13,
    input  wire [7:0] wrap_input_4_14,
    input  wire [7:0] wrap_input_4_15,
    input  wire [7:0] wrap_input_5_0,
    input  wire [7:0] wrap_input_5_1,
    input  wire [7:0] wrap_input_5_2,
    input  wire [7:0] wrap_input_5_3,
    input  wire [7:0] wrap_input_5_4,
    input  wire [7:0] wrap_input_5_5,
    input  wire [7:0] wrap_input_5_6,
    input  wire [7:0] wrap_input_5_7,
    input  wire [7:0] wrap_input_5_8,
    input  wire [7:0] wrap_input_5_9,
    input  wire [7:0] wrap_input_5_10,
    input  wire [7:0] wrap_input_5_11,
    input  wire [7:0] wrap_input_5_12,
    input  wire [7:0] wrap_input_5_13,
    input  wire [7:0] wrap_input_5_14,
    input  wire [7:0] wrap_input_5_15,
    input  wire [7:0] wrap_input_6_0,
    input  wire [7:0] wrap_input_6_1,
    input  wire [7:0] wrap_input_6_2,
    input  wire [7:0] wrap_input_6_3,
    input  wire [7:0] wrap_input_6_4,
    input  wire [7:0] wrap_input_6_5,
    input  wire [7:0] wrap_input_6_6,
    input  wire [7:0] wrap_input_6_7,
    input  wire [7:0] wrap_input_6_8,
    input  wire [7:0] wrap_input_6_9,
    input  wire [7:0] wrap_input_6_10,
    input  wire [7:0] wrap_input_6_11,
    input  wire [7:0] wrap_input_6_12,
    input  wire [7:0] wrap_input_6_13,
    input  wire [7:0] wrap_input_6_14,
    input  wire [7:0] wrap_input_6_15,
    input  wire [7:0] wrap_input_7_0,
    input  wire [7:0] wrap_input_7_1,
    input  wire [7:0] wrap_input_7_2,
    input  wire [7:0] wrap_input_7_3,
    input  wire [7:0] wrap_input_7_4,
    input  wire [7:0] wrap_input_7_5,
    input  wire [7:0] wrap_input_7_6,
    input  wire [7:0] wrap_input_7_7,
    input  wire [7:0] wrap_input_7_8,
    input  wire [7:0] wrap_input_7_9,
    input  wire [7:0] wrap_input_7_10,
    input  wire [7:0] wrap_input_7_11,
    input  wire [7:0] wrap_input_7_12,
    input  wire [7:0] wrap_input_7_13,
    input  wire [7:0] wrap_input_7_14,
    input  wire [7:0] wrap_input_7_15,
    input  wire [7:0] wrap_edge_masks_0,
    input  wire [7:0] wrap_edge_masks_1,
    input  wire [7:0] wrap_edge_masks_2,
    input  wire [7:0] wrap_edge_masks_3,
    input  wire [7:0] wrap_edge_masks_4,
    input  wire [7:0] wrap_edge_masks_5,
    input  wire [7:0] wrap_edge_masks_6,
    input  wire [7:0] wrap_edge_masks_7,
    output wire [7:0] wrap_output_0_0,
    output wire [7:0] wrap_output_0_1,
    output wire [7:0] wrap_output_0_2,
    output wire [7:0] wrap_output_0_3,
    output wire [7:0] wrap_output_0_4,
    output wire [7:0] wrap_output_0_5,
    output wire [7:0] wrap_output_0_6,
    output wire [7:0] wrap_output_1_0,
    output wire [7:0] wrap_output_1_1,
    output wire [7:0] wrap_output_1_2,
    output wire [7:0] wrap_output_1_3,
    output wire [7:0] wrap_output_1_4,
    output wire [7:0] wrap_output_1_5,
    output wire [7:0] wrap_output_1_6,
    output wire [7:0] wrap_output_2_0,
    output wire [7:0] wrap_output_2_1,
    output wire [7:0] wrap_output_2_2,
    output wire [7:0] wrap_output_2_3,
    output wire [7:0] wrap_output_2_4,
    output wire [7:0] wrap_output_2_5,
    output wire [7:0] wrap_output_2_6,
    output wire [7:0] wrap_output_3_0,
    output wire [7:0] wrap_output_3_1,
    output wire [7:0] wrap_output_3_2,
    output wire [7:0] wrap_output_3_3,
    output wire [7:0] wrap_output_3_4,
    output wire [7:0] wrap_output_3_5,
    output wire [7:0] wrap_output_3_6,
    output wire [7:0] wrap_output_4_0,
    output wire [7:0] wrap_output_4_1,
    output wire [7:0] wrap_output_4_2,
    output wire [7:0] wrap_output_4_3,
    output wire [7:0] wrap_output_4_4,
    output wire [7:0] wrap_output_4_5,
    output wire [7:0] wrap_output_4_6,
    output wire [7:0] wrap_output_5_0,
    output wire [7:0] wrap_output_5_1,
    output wire [7:0] wrap_output_5_2,
    output wire [7:0] wrap_output_5_3,
    output wire [7:0] wrap_output_5_4,
    output wire [7:0] wrap_output_5_5,
    output wire [7:0] wrap_output_5_6,
    output wire [7:0] wrap_output_6_0,
    output wire [7:0] wrap_output_6_1,
    output wire [7:0] wrap_output_6_2,
    output wire [7:0] wrap_output_6_3,
    output wire [7:0] wrap_output_6_4,
    output wire [7:0] wrap_output_6_5,
    output wire [7:0] wrap_output_6_6,
    output wire [7:0] wrap_output_7_0,
    output wire [7:0] wrap_output_7_1,
    output wire [7:0] wrap_output_7_2,
    output wire [7:0] wrap_output_7_3,
    output wire [7:0] wrap_output_7_4,
    output wire [7:0] wrap_output_7_5,
    output wire [7:0] wrap_output_7_6
);

    wire ap_clk_buf;
    BUFG bufg_ap_clk (.I(clk_in), .O(ap_clk_buf));

    reg rst_reg;
    always @(posedge ap_clk_buf) rst_reg <= rst_in;

    reg [7:0] input_0_0_reg;
    reg [7:0] input_0_1_reg;
    reg [7:0] input_0_2_reg;
    reg [7:0] input_0_3_reg;
    reg [7:0] input_0_4_reg;
    reg [7:0] input_0_5_reg;
    reg [7:0] input_0_6_reg;
    reg [7:0] input_0_7_reg;
    reg [7:0] input_0_8_reg;
    reg [7:0] input_0_9_reg;
    reg [7:0] input_0_10_reg;
    reg [7:0] input_0_11_reg;
    reg [7:0] input_0_12_reg;
    reg [7:0] input_0_13_reg;
    reg [7:0] input_0_14_reg;
    reg [7:0] input_0_15_reg;
    reg [7:0] input_1_0_reg;
    reg [7:0] input_1_1_reg;
    reg [7:0] input_1_2_reg;
    reg [7:0] input_1_3_reg;
    reg [7:0] input_1_4_reg;
    reg [7:0] input_1_5_reg;
    reg [7:0] input_1_6_reg;
    reg [7:0] input_1_7_reg;
    reg [7:0] input_1_8_reg;
    reg [7:0] input_1_9_reg;
    reg [7:0] input_1_10_reg;
    reg [7:0] input_1_11_reg;
    reg [7:0] input_1_12_reg;
    reg [7:0] input_1_13_reg;
    reg [7:0] input_1_14_reg;
    reg [7:0] input_1_15_reg;
    reg [7:0] input_2_0_reg;
    reg [7:0] input_2_1_reg;
    reg [7:0] input_2_2_reg;
    reg [7:0] input_2_3_reg;
    reg [7:0] input_2_4_reg;
    reg [7:0] input_2_5_reg;
    reg [7:0] input_2_6_reg;
    reg [7:0] input_2_7_reg;
    reg [7:0] input_2_8_reg;
    reg [7:0] input_2_9_reg;
    reg [7:0] input_2_10_reg;
    reg [7:0] input_2_11_reg;
    reg [7:0] input_2_12_reg;
    reg [7:0] input_2_13_reg;
    reg [7:0] input_2_14_reg;
    reg [7:0] input_2_15_reg;
    reg [7:0] input_3_0_reg;
    reg [7:0] input_3_1_reg;
    reg [7:0] input_3_2_reg;
    reg [7:0] input_3_3_reg;
    reg [7:0] input_3_4_reg;
    reg [7:0] input_3_5_reg;
    reg [7:0] input_3_6_reg;
    reg [7:0] input_3_7_reg;
    reg [7:0] input_3_8_reg;
    reg [7:0] input_3_9_reg;
    reg [7:0] input_3_10_reg;
    reg [7:0] input_3_11_reg;
    reg [7:0] input_3_12_reg;
    reg [7:0] input_3_13_reg;
    reg [7:0] input_3_14_reg;
    reg [7:0] input_3_15_reg;
    reg [7:0] input_4_0_reg;
    reg [7:0] input_4_1_reg;
    reg [7:0] input_4_2_reg;
    reg [7:0] input_4_3_reg;
    reg [7:0] input_4_4_reg;
    reg [7:0] input_4_5_reg;
    reg [7:0] input_4_6_reg;
    reg [7:0] input_4_7_reg;
    reg [7:0] input_4_8_reg;
    reg [7:0] input_4_9_reg;
    reg [7:0] input_4_10_reg;
    reg [7:0] input_4_11_reg;
    reg [7:0] input_4_12_reg;
    reg [7:0] input_4_13_reg;
    reg [7:0] input_4_14_reg;
    reg [7:0] input_4_15_reg;
    reg [7:0] input_5_0_reg;
    reg [7:0] input_5_1_reg;
    reg [7:0] input_5_2_reg;
    reg [7:0] input_5_3_reg;
    reg [7:0] input_5_4_reg;
    reg [7:0] input_5_5_reg;
    reg [7:0] input_5_6_reg;
    reg [7:0] input_5_7_reg;
    reg [7:0] input_5_8_reg;
    reg [7:0] input_5_9_reg;
    reg [7:0] input_5_10_reg;
    reg [7:0] input_5_11_reg;
    reg [7:0] input_5_12_reg;
    reg [7:0] input_5_13_reg;
    reg [7:0] input_5_14_reg;
    reg [7:0] input_5_15_reg;
    reg [7:0] input_6_0_reg;
    reg [7:0] input_6_1_reg;
    reg [7:0] input_6_2_reg;
    reg [7:0] input_6_3_reg;
    reg [7:0] input_6_4_reg;
    reg [7:0] input_6_5_reg;
    reg [7:0] input_6_6_reg;
    reg [7:0] input_6_7_reg;
    reg [7:0] input_6_8_reg;
    reg [7:0] input_6_9_reg;
    reg [7:0] input_6_10_reg;
    reg [7:0] input_6_11_reg;
    reg [7:0] input_6_12_reg;
    reg [7:0] input_6_13_reg;
    reg [7:0] input_6_14_reg;
    reg [7:0] input_6_15_reg;
    reg [7:0] input_7_0_reg;
    reg [7:0] input_7_1_reg;
    reg [7:0] input_7_2_reg;
    reg [7:0] input_7_3_reg;
    reg [7:0] input_7_4_reg;
    reg [7:0] input_7_5_reg;
    reg [7:0] input_7_6_reg;
    reg [7:0] input_7_7_reg;
    reg [7:0] input_7_8_reg;
    reg [7:0] input_7_9_reg;
    reg [7:0] input_7_10_reg;
    reg [7:0] input_7_11_reg;
    reg [7:0] input_7_12_reg;
    reg [7:0] input_7_13_reg;
    reg [7:0] input_7_14_reg;
    reg [7:0] input_7_15_reg;
    reg [7:0] edge_masks_0_reg;
    reg [7:0] edge_masks_1_reg;
    reg [7:0] edge_masks_2_reg;
    reg [7:0] edge_masks_3_reg;
    reg [7:0] edge_masks_4_reg;
    reg [7:0] edge_masks_5_reg;
    reg [7:0] edge_masks_6_reg;
    reg [7:0] edge_masks_7_reg;
    always @(posedge ap_clk_buf) begin
        input_0_0_reg <= wrap_input_0_0;
        input_0_1_reg <= wrap_input_0_1;
        input_0_2_reg <= wrap_input_0_2;
        input_0_3_reg <= wrap_input_0_3;
        input_0_4_reg <= wrap_input_0_4;
        input_0_5_reg <= wrap_input_0_5;
        input_0_6_reg <= wrap_input_0_6;
        input_0_7_reg <= wrap_input_0_7;
        input_0_8_reg <= wrap_input_0_8;
        input_0_9_reg <= wrap_input_0_9;
        input_0_10_reg <= wrap_input_0_10;
        input_0_11_reg <= wrap_input_0_11;
        input_0_12_reg <= wrap_input_0_12;
        input_0_13_reg <= wrap_input_0_13;
        input_0_14_reg <= wrap_input_0_14;
        input_0_15_reg <= wrap_input_0_15;
        input_1_0_reg <= wrap_input_1_0;
        input_1_1_reg <= wrap_input_1_1;
        input_1_2_reg <= wrap_input_1_2;
        input_1_3_reg <= wrap_input_1_3;
        input_1_4_reg <= wrap_input_1_4;
        input_1_5_reg <= wrap_input_1_5;
        input_1_6_reg <= wrap_input_1_6;
        input_1_7_reg <= wrap_input_1_7;
        input_1_8_reg <= wrap_input_1_8;
        input_1_9_reg <= wrap_input_1_9;
        input_1_10_reg <= wrap_input_1_10;
        input_1_11_reg <= wrap_input_1_11;
        input_1_12_reg <= wrap_input_1_12;
        input_1_13_reg <= wrap_input_1_13;
        input_1_14_reg <= wrap_input_1_14;
        input_1_15_reg <= wrap_input_1_15;
        input_2_0_reg <= wrap_input_2_0;
        input_2_1_reg <= wrap_input_2_1;
        input_2_2_reg <= wrap_input_2_2;
        input_2_3_reg <= wrap_input_2_3;
        input_2_4_reg <= wrap_input_2_4;
        input_2_5_reg <= wrap_input_2_5;
        input_2_6_reg <= wrap_input_2_6;
        input_2_7_reg <= wrap_input_2_7;
        input_2_8_reg <= wrap_input_2_8;
        input_2_9_reg <= wrap_input_2_9;
        input_2_10_reg <= wrap_input_2_10;
        input_2_11_reg <= wrap_input_2_11;
        input_2_12_reg <= wrap_input_2_12;
        input_2_13_reg <= wrap_input_2_13;
        input_2_14_reg <= wrap_input_2_14;
        input_2_15_reg <= wrap_input_2_15;
        input_3_0_reg <= wrap_input_3_0;
        input_3_1_reg <= wrap_input_3_1;
        input_3_2_reg <= wrap_input_3_2;
        input_3_3_reg <= wrap_input_3_3;
        input_3_4_reg <= wrap_input_3_4;
        input_3_5_reg <= wrap_input_3_5;
        input_3_6_reg <= wrap_input_3_6;
        input_3_7_reg <= wrap_input_3_7;
        input_3_8_reg <= wrap_input_3_8;
        input_3_9_reg <= wrap_input_3_9;
        input_3_10_reg <= wrap_input_3_10;
        input_3_11_reg <= wrap_input_3_11;
        input_3_12_reg <= wrap_input_3_12;
        input_3_13_reg <= wrap_input_3_13;
        input_3_14_reg <= wrap_input_3_14;
        input_3_15_reg <= wrap_input_3_15;
        input_4_0_reg <= wrap_input_4_0;
        input_4_1_reg <= wrap_input_4_1;
        input_4_2_reg <= wrap_input_4_2;
        input_4_3_reg <= wrap_input_4_3;
        input_4_4_reg <= wrap_input_4_4;
        input_4_5_reg <= wrap_input_4_5;
        input_4_6_reg <= wrap_input_4_6;
        input_4_7_reg <= wrap_input_4_7;
        input_4_8_reg <= wrap_input_4_8;
        input_4_9_reg <= wrap_input_4_9;
        input_4_10_reg <= wrap_input_4_10;
        input_4_11_reg <= wrap_input_4_11;
        input_4_12_reg <= wrap_input_4_12;
        input_4_13_reg <= wrap_input_4_13;
        input_4_14_reg <= wrap_input_4_14;
        input_4_15_reg <= wrap_input_4_15;
        input_5_0_reg <= wrap_input_5_0;
        input_5_1_reg <= wrap_input_5_1;
        input_5_2_reg <= wrap_input_5_2;
        input_5_3_reg <= wrap_input_5_3;
        input_5_4_reg <= wrap_input_5_4;
        input_5_5_reg <= wrap_input_5_5;
        input_5_6_reg <= wrap_input_5_6;
        input_5_7_reg <= wrap_input_5_7;
        input_5_8_reg <= wrap_input_5_8;
        input_5_9_reg <= wrap_input_5_9;
        input_5_10_reg <= wrap_input_5_10;
        input_5_11_reg <= wrap_input_5_11;
        input_5_12_reg <= wrap_input_5_12;
        input_5_13_reg <= wrap_input_5_13;
        input_5_14_reg <= wrap_input_5_14;
        input_5_15_reg <= wrap_input_5_15;
        input_6_0_reg <= wrap_input_6_0;
        input_6_1_reg <= wrap_input_6_1;
        input_6_2_reg <= wrap_input_6_2;
        input_6_3_reg <= wrap_input_6_3;
        input_6_4_reg <= wrap_input_6_4;
        input_6_5_reg <= wrap_input_6_5;
        input_6_6_reg <= wrap_input_6_6;
        input_6_7_reg <= wrap_input_6_7;
        input_6_8_reg <= wrap_input_6_8;
        input_6_9_reg <= wrap_input_6_9;
        input_6_10_reg <= wrap_input_6_10;
        input_6_11_reg <= wrap_input_6_11;
        input_6_12_reg <= wrap_input_6_12;
        input_6_13_reg <= wrap_input_6_13;
        input_6_14_reg <= wrap_input_6_14;
        input_6_15_reg <= wrap_input_6_15;
        input_7_0_reg <= wrap_input_7_0;
        input_7_1_reg <= wrap_input_7_1;
        input_7_2_reg <= wrap_input_7_2;
        input_7_3_reg <= wrap_input_7_3;
        input_7_4_reg <= wrap_input_7_4;
        input_7_5_reg <= wrap_input_7_5;
        input_7_6_reg <= wrap_input_7_6;
        input_7_7_reg <= wrap_input_7_7;
        input_7_8_reg <= wrap_input_7_8;
        input_7_9_reg <= wrap_input_7_9;
        input_7_10_reg <= wrap_input_7_10;
        input_7_11_reg <= wrap_input_7_11;
        input_7_12_reg <= wrap_input_7_12;
        input_7_13_reg <= wrap_input_7_13;
        input_7_14_reg <= wrap_input_7_14;
        input_7_15_reg <= wrap_input_7_15;
        edge_masks_0_reg <= wrap_edge_masks_0;
        edge_masks_1_reg <= wrap_edge_masks_1;
        edge_masks_2_reg <= wrap_edge_masks_2;
        edge_masks_3_reg <= wrap_edge_masks_3;
        edge_masks_4_reg <= wrap_edge_masks_4;
        edge_masks_5_reg <= wrap_edge_masks_5;
        edge_masks_6_reg <= wrap_edge_masks_6;
        edge_masks_7_reg <= wrap_edge_masks_7;
    end

    reg [7:0] output_0_0_reg;
    reg [7:0] output_0_1_reg;
    reg [7:0] output_0_2_reg;
    reg [7:0] output_0_3_reg;
    reg [7:0] output_0_4_reg;
    reg [7:0] output_0_5_reg;
    reg [7:0] output_0_6_reg;
    reg [7:0] output_1_0_reg;
    reg [7:0] output_1_1_reg;
    reg [7:0] output_1_2_reg;
    reg [7:0] output_1_3_reg;
    reg [7:0] output_1_4_reg;
    reg [7:0] output_1_5_reg;
    reg [7:0] output_1_6_reg;
    reg [7:0] output_2_0_reg;
    reg [7:0] output_2_1_reg;
    reg [7:0] output_2_2_reg;
    reg [7:0] output_2_3_reg;
    reg [7:0] output_2_4_reg;
    reg [7:0] output_2_5_reg;
    reg [7:0] output_2_6_reg;
    reg [7:0] output_3_0_reg;
    reg [7:0] output_3_1_reg;
    reg [7:0] output_3_2_reg;
    reg [7:0] output_3_3_reg;
    reg [7:0] output_3_4_reg;
    reg [7:0] output_3_5_reg;
    reg [7:0] output_3_6_reg;
    reg [7:0] output_4_0_reg;
    reg [7:0] output_4_1_reg;
    reg [7:0] output_4_2_reg;
    reg [7:0] output_4_3_reg;
    reg [7:0] output_4_4_reg;
    reg [7:0] output_4_5_reg;
    reg [7:0] output_4_6_reg;
    reg [7:0] output_5_0_reg;
    reg [7:0] output_5_1_reg;
    reg [7:0] output_5_2_reg;
    reg [7:0] output_5_3_reg;
    reg [7:0] output_5_4_reg;
    reg [7:0] output_5_5_reg;
    reg [7:0] output_5_6_reg;
    reg [7:0] output_6_0_reg;
    reg [7:0] output_6_1_reg;
    reg [7:0] output_6_2_reg;
    reg [7:0] output_6_3_reg;
    reg [7:0] output_6_4_reg;
    reg [7:0] output_6_5_reg;
    reg [7:0] output_6_6_reg;
    reg [7:0] output_7_0_reg;
    reg [7:0] output_7_1_reg;
    reg [7:0] output_7_2_reg;
    reg [7:0] output_7_3_reg;
    reg [7:0] output_7_4_reg;
    reg [7:0] output_7_5_reg;
    reg [7:0] output_7_6_reg;
    wire [7:0] output_0_0_comb;
    wire [7:0] output_0_1_comb;
    wire [7:0] output_0_2_comb;
    wire [7:0] output_0_3_comb;
    wire [7:0] output_0_4_comb;
    wire [7:0] output_0_5_comb;
    wire [7:0] output_0_6_comb;
    wire [7:0] output_1_0_comb;
    wire [7:0] output_1_1_comb;
    wire [7:0] output_1_2_comb;
    wire [7:0] output_1_3_comb;
    wire [7:0] output_1_4_comb;
    wire [7:0] output_1_5_comb;
    wire [7:0] output_1_6_comb;
    wire [7:0] output_2_0_comb;
    wire [7:0] output_2_1_comb;
    wire [7:0] output_2_2_comb;
    wire [7:0] output_2_3_comb;
    wire [7:0] output_2_4_comb;
    wire [7:0] output_2_5_comb;
    wire [7:0] output_2_6_comb;
    wire [7:0] output_3_0_comb;
    wire [7:0] output_3_1_comb;
    wire [7:0] output_3_2_comb;
    wire [7:0] output_3_3_comb;
    wire [7:0] output_3_4_comb;
    wire [7:0] output_3_5_comb;
    wire [7:0] output_3_6_comb;
    wire [7:0] output_4_0_comb;
    wire [7:0] output_4_1_comb;
    wire [7:0] output_4_2_comb;
    wire [7:0] output_4_3_comb;
    wire [7:0] output_4_4_comb;
    wire [7:0] output_4_5_comb;
    wire [7:0] output_4_6_comb;
    wire [7:0] output_5_0_comb;
    wire [7:0] output_5_1_comb;
    wire [7:0] output_5_2_comb;
    wire [7:0] output_5_3_comb;
    wire [7:0] output_5_4_comb;
    wire [7:0] output_5_5_comb;
    wire [7:0] output_5_6_comb;
    wire [7:0] output_6_0_comb;
    wire [7:0] output_6_1_comb;
    wire [7:0] output_6_2_comb;
    wire [7:0] output_6_3_comb;
    wire [7:0] output_6_4_comb;
    wire [7:0] output_6_5_comb;
    wire [7:0] output_6_6_comb;
    wire [7:0] output_7_0_comb;
    wire [7:0] output_7_1_comb;
    wire [7:0] output_7_2_comb;
    wire [7:0] output_7_3_comb;
    wire [7:0] output_7_4_comb;
    wire [7:0] output_7_5_comb;
    wire [7:0] output_7_6_comb;
    always @(posedge ap_clk_buf) begin
        output_0_0_reg <= output_0_0_comb;
        output_0_1_reg <= output_0_1_comb;
        output_0_2_reg <= output_0_2_comb;
        output_0_3_reg <= output_0_3_comb;
        output_0_4_reg <= output_0_4_comb;
        output_0_5_reg <= output_0_5_comb;
        output_0_6_reg <= output_0_6_comb;
        output_1_0_reg <= output_1_0_comb;
        output_1_1_reg <= output_1_1_comb;
        output_1_2_reg <= output_1_2_comb;
        output_1_3_reg <= output_1_3_comb;
        output_1_4_reg <= output_1_4_comb;
        output_1_5_reg <= output_1_5_comb;
        output_1_6_reg <= output_1_6_comb;
        output_2_0_reg <= output_2_0_comb;
        output_2_1_reg <= output_2_1_comb;
        output_2_2_reg <= output_2_2_comb;
        output_2_3_reg <= output_2_3_comb;
        output_2_4_reg <= output_2_4_comb;
        output_2_5_reg <= output_2_5_comb;
        output_2_6_reg <= output_2_6_comb;
        output_3_0_reg <= output_3_0_comb;
        output_3_1_reg <= output_3_1_comb;
        output_3_2_reg <= output_3_2_comb;
        output_3_3_reg <= output_3_3_comb;
        output_3_4_reg <= output_3_4_comb;
        output_3_5_reg <= output_3_5_comb;
        output_3_6_reg <= output_3_6_comb;
        output_4_0_reg <= output_4_0_comb;
        output_4_1_reg <= output_4_1_comb;
        output_4_2_reg <= output_4_2_comb;
        output_4_3_reg <= output_4_3_comb;
        output_4_4_reg <= output_4_4_comb;
        output_4_5_reg <= output_4_5_comb;
        output_4_6_reg <= output_4_6_comb;
        output_5_0_reg <= output_5_0_comb;
        output_5_1_reg <= output_5_1_comb;
        output_5_2_reg <= output_5_2_comb;
        output_5_3_reg <= output_5_3_comb;
        output_5_4_reg <= output_5_4_comb;
        output_5_5_reg <= output_5_5_comb;
        output_5_6_reg <= output_5_6_comb;
        output_6_0_reg <= output_6_0_comb;
        output_6_1_reg <= output_6_1_comb;
        output_6_2_reg <= output_6_2_comb;
        output_6_3_reg <= output_6_3_comb;
        output_6_4_reg <= output_6_4_comb;
        output_6_5_reg <= output_6_5_comb;
        output_6_6_reg <= output_6_6_comb;
        output_7_0_reg <= output_7_0_comb;
        output_7_1_reg <= output_7_1_comb;
        output_7_2_reg <= output_7_2_comb;
        output_7_3_reg <= output_7_3_comb;
        output_7_4_reg <= output_7_4_comb;
        output_7_5_reg <= output_7_5_comb;
        output_7_6_reg <= output_7_6_comb;
    end
    assign wrap_output_0_0 = output_0_0_reg;
    assign wrap_output_0_1 = output_0_1_reg;
    assign wrap_output_0_2 = output_0_2_reg;
    assign wrap_output_0_3 = output_0_3_reg;
    assign wrap_output_0_4 = output_0_4_reg;
    assign wrap_output_0_5 = output_0_5_reg;
    assign wrap_output_0_6 = output_0_6_reg;
    assign wrap_output_1_0 = output_1_0_reg;
    assign wrap_output_1_1 = output_1_1_reg;
    assign wrap_output_1_2 = output_1_2_reg;
    assign wrap_output_1_3 = output_1_3_reg;
    assign wrap_output_1_4 = output_1_4_reg;
    assign wrap_output_1_5 = output_1_5_reg;
    assign wrap_output_1_6 = output_1_6_reg;
    assign wrap_output_2_0 = output_2_0_reg;
    assign wrap_output_2_1 = output_2_1_reg;
    assign wrap_output_2_2 = output_2_2_reg;
    assign wrap_output_2_3 = output_2_3_reg;
    assign wrap_output_2_4 = output_2_4_reg;
    assign wrap_output_2_5 = output_2_5_reg;
    assign wrap_output_2_6 = output_2_6_reg;
    assign wrap_output_3_0 = output_3_0_reg;
    assign wrap_output_3_1 = output_3_1_reg;
    assign wrap_output_3_2 = output_3_2_reg;
    assign wrap_output_3_3 = output_3_3_reg;
    assign wrap_output_3_4 = output_3_4_reg;
    assign wrap_output_3_5 = output_3_5_reg;
    assign wrap_output_3_6 = output_3_6_reg;
    assign wrap_output_4_0 = output_4_0_reg;
    assign wrap_output_4_1 = output_4_1_reg;
    assign wrap_output_4_2 = output_4_2_reg;
    assign wrap_output_4_3 = output_4_3_reg;
    assign wrap_output_4_4 = output_4_4_reg;
    assign wrap_output_4_5 = output_4_5_reg;
    assign wrap_output_4_6 = output_4_6_reg;
    assign wrap_output_5_0 = output_5_0_reg;
    assign wrap_output_5_1 = output_5_1_reg;
    assign wrap_output_5_2 = output_5_2_reg;
    assign wrap_output_5_3 = output_5_3_reg;
    assign wrap_output_5_4 = output_5_4_reg;
    assign wrap_output_5_5 = output_5_5_reg;
    assign wrap_output_5_6 = output_5_6_reg;
    assign wrap_output_6_0 = output_6_0_reg;
    assign wrap_output_6_1 = output_6_1_reg;
    assign wrap_output_6_2 = output_6_2_reg;
    assign wrap_output_6_3 = output_6_3_reg;
    assign wrap_output_6_4 = output_6_4_reg;
    assign wrap_output_6_5 = output_6_5_reg;
    assign wrap_output_6_6 = output_6_6_reg;
    assign wrap_output_7_0 = output_7_0_reg;
    assign wrap_output_7_1 = output_7_1_reg;
    assign wrap_output_7_2 = output_7_2_reg;
    assign wrap_output_7_3 = output_7_3_reg;
    assign wrap_output_7_4 = output_7_4_reg;
    assign wrap_output_7_5 = output_7_5_reg;
    assign wrap_output_7_6 = output_7_6_reg;

    graphsage_po2_qat_partitioned u_accel (
        .ap_clk(ap_clk_buf),
        .ap_rst(rst_reg),
        .input_0_0(input_0_0_reg),
        .input_0_1(input_0_1_reg),
        .input_0_2(input_0_2_reg),
        .input_0_3(input_0_3_reg),
        .input_0_4(input_0_4_reg),
        .input_0_5(input_0_5_reg),
        .input_0_6(input_0_6_reg),
        .input_0_7(input_0_7_reg),
        .input_0_8(input_0_8_reg),
        .input_0_9(input_0_9_reg),
        .input_0_10(input_0_10_reg),
        .input_0_11(input_0_11_reg),
        .input_0_12(input_0_12_reg),
        .input_0_13(input_0_13_reg),
        .input_0_14(input_0_14_reg),
        .input_0_15(input_0_15_reg),
        .input_1_0(input_1_0_reg),
        .input_1_1(input_1_1_reg),
        .input_1_2(input_1_2_reg),
        .input_1_3(input_1_3_reg),
        .input_1_4(input_1_4_reg),
        .input_1_5(input_1_5_reg),
        .input_1_6(input_1_6_reg),
        .input_1_7(input_1_7_reg),
        .input_1_8(input_1_8_reg),
        .input_1_9(input_1_9_reg),
        .input_1_10(input_1_10_reg),
        .input_1_11(input_1_11_reg),
        .input_1_12(input_1_12_reg),
        .input_1_13(input_1_13_reg),
        .input_1_14(input_1_14_reg),
        .input_1_15(input_1_15_reg),
        .input_2_0(input_2_0_reg),
        .input_2_1(input_2_1_reg),
        .input_2_2(input_2_2_reg),
        .input_2_3(input_2_3_reg),
        .input_2_4(input_2_4_reg),
        .input_2_5(input_2_5_reg),
        .input_2_6(input_2_6_reg),
        .input_2_7(input_2_7_reg),
        .input_2_8(input_2_8_reg),
        .input_2_9(input_2_9_reg),
        .input_2_10(input_2_10_reg),
        .input_2_11(input_2_11_reg),
        .input_2_12(input_2_12_reg),
        .input_2_13(input_2_13_reg),
        .input_2_14(input_2_14_reg),
        .input_2_15(input_2_15_reg),
        .input_3_0(input_3_0_reg),
        .input_3_1(input_3_1_reg),
        .input_3_2(input_3_2_reg),
        .input_3_3(input_3_3_reg),
        .input_3_4(input_3_4_reg),
        .input_3_5(input_3_5_reg),
        .input_3_6(input_3_6_reg),
        .input_3_7(input_3_7_reg),
        .input_3_8(input_3_8_reg),
        .input_3_9(input_3_9_reg),
        .input_3_10(input_3_10_reg),
        .input_3_11(input_3_11_reg),
        .input_3_12(input_3_12_reg),
        .input_3_13(input_3_13_reg),
        .input_3_14(input_3_14_reg),
        .input_3_15(input_3_15_reg),
        .input_4_0(input_4_0_reg),
        .input_4_1(input_4_1_reg),
        .input_4_2(input_4_2_reg),
        .input_4_3(input_4_3_reg),
        .input_4_4(input_4_4_reg),
        .input_4_5(input_4_5_reg),
        .input_4_6(input_4_6_reg),
        .input_4_7(input_4_7_reg),
        .input_4_8(input_4_8_reg),
        .input_4_9(input_4_9_reg),
        .input_4_10(input_4_10_reg),
        .input_4_11(input_4_11_reg),
        .input_4_12(input_4_12_reg),
        .input_4_13(input_4_13_reg),
        .input_4_14(input_4_14_reg),
        .input_4_15(input_4_15_reg),
        .input_5_0(input_5_0_reg),
        .input_5_1(input_5_1_reg),
        .input_5_2(input_5_2_reg),
        .input_5_3(input_5_3_reg),
        .input_5_4(input_5_4_reg),
        .input_5_5(input_5_5_reg),
        .input_5_6(input_5_6_reg),
        .input_5_7(input_5_7_reg),
        .input_5_8(input_5_8_reg),
        .input_5_9(input_5_9_reg),
        .input_5_10(input_5_10_reg),
        .input_5_11(input_5_11_reg),
        .input_5_12(input_5_12_reg),
        .input_5_13(input_5_13_reg),
        .input_5_14(input_5_14_reg),
        .input_5_15(input_5_15_reg),
        .input_6_0(input_6_0_reg),
        .input_6_1(input_6_1_reg),
        .input_6_2(input_6_2_reg),
        .input_6_3(input_6_3_reg),
        .input_6_4(input_6_4_reg),
        .input_6_5(input_6_5_reg),
        .input_6_6(input_6_6_reg),
        .input_6_7(input_6_7_reg),
        .input_6_8(input_6_8_reg),
        .input_6_9(input_6_9_reg),
        .input_6_10(input_6_10_reg),
        .input_6_11(input_6_11_reg),
        .input_6_12(input_6_12_reg),
        .input_6_13(input_6_13_reg),
        .input_6_14(input_6_14_reg),
        .input_6_15(input_6_15_reg),
        .input_7_0(input_7_0_reg),
        .input_7_1(input_7_1_reg),
        .input_7_2(input_7_2_reg),
        .input_7_3(input_7_3_reg),
        .input_7_4(input_7_4_reg),
        .input_7_5(input_7_5_reg),
        .input_7_6(input_7_6_reg),
        .input_7_7(input_7_7_reg),
        .input_7_8(input_7_8_reg),
        .input_7_9(input_7_9_reg),
        .input_7_10(input_7_10_reg),
        .input_7_11(input_7_11_reg),
        .input_7_12(input_7_12_reg),
        .input_7_13(input_7_13_reg),
        .input_7_14(input_7_14_reg),
        .input_7_15(input_7_15_reg),
        .edge_masks_0(edge_masks_0_reg),
        .edge_masks_1(edge_masks_1_reg),
        .edge_masks_2(edge_masks_2_reg),
        .edge_masks_3(edge_masks_3_reg),
        .edge_masks_4(edge_masks_4_reg),
        .edge_masks_5(edge_masks_5_reg),
        .edge_masks_6(edge_masks_6_reg),
        .edge_masks_7(edge_masks_7_reg),
        .output_0_0(output_0_0_comb),
        .output_0_1(output_0_1_comb),
        .output_0_2(output_0_2_comb),
        .output_0_3(output_0_3_comb),
        .output_0_4(output_0_4_comb),
        .output_0_5(output_0_5_comb),
        .output_0_6(output_0_6_comb),
        .output_1_0(output_1_0_comb),
        .output_1_1(output_1_1_comb),
        .output_1_2(output_1_2_comb),
        .output_1_3(output_1_3_comb),
        .output_1_4(output_1_4_comb),
        .output_1_5(output_1_5_comb),
        .output_1_6(output_1_6_comb),
        .output_2_0(output_2_0_comb),
        .output_2_1(output_2_1_comb),
        .output_2_2(output_2_2_comb),
        .output_2_3(output_2_3_comb),
        .output_2_4(output_2_4_comb),
        .output_2_5(output_2_5_comb),
        .output_2_6(output_2_6_comb),
        .output_3_0(output_3_0_comb),
        .output_3_1(output_3_1_comb),
        .output_3_2(output_3_2_comb),
        .output_3_3(output_3_3_comb),
        .output_3_4(output_3_4_comb),
        .output_3_5(output_3_5_comb),
        .output_3_6(output_3_6_comb),
        .output_4_0(output_4_0_comb),
        .output_4_1(output_4_1_comb),
        .output_4_2(output_4_2_comb),
        .output_4_3(output_4_3_comb),
        .output_4_4(output_4_4_comb),
        .output_4_5(output_4_5_comb),
        .output_4_6(output_4_6_comb),
        .output_5_0(output_5_0_comb),
        .output_5_1(output_5_1_comb),
        .output_5_2(output_5_2_comb),
        .output_5_3(output_5_3_comb),
        .output_5_4(output_5_4_comb),
        .output_5_5(output_5_5_comb),
        .output_5_6(output_5_6_comb),
        .output_6_0(output_6_0_comb),
        .output_6_1(output_6_1_comb),
        .output_6_2(output_6_2_comb),
        .output_6_3(output_6_3_comb),
        .output_6_4(output_6_4_comb),
        .output_6_5(output_6_5_comb),
        .output_6_6(output_6_6_comb),
        .output_7_0(output_7_0_comb),
        .output_7_1(output_7_1_comb),
        .output_7_2(output_7_2_comb),
        .output_7_3(output_7_3_comb),
        .output_7_4(output_7_4_comb),
        .output_7_5(output_7_5_comb),
        .output_7_6(output_7_6_comb)
    );

endmodule
